### ISSUE TITLE
"Uncaught Error: No protocol method WritePort.put! defined for type null:" when submitting query

### ISSUE THREAD

**Issue by fdb** [thi-ng/ws-ldn-2#1]
I'm trying to work with the query on the latest master (801c1a7a7c560a173d33534994cb49feb5e2e62e) but run in to an issue. 

I've added the file `resources/data/sales-2013-xl.edn` (based on the edn file we made during the workshop).

I've launched the server using `lein repl`, then on the REPL:

```
(require '[ws-ldn-2.core])
(in-ns 'ws-ldn-2.core)
(launch)
```

I've verified that it added the facts:

```
15-Nov-16 15:36:46 prodeo.local INFO [thi.ng.fabric.ld.core] - adding 100 facts from [..]london-boroughs.nt
15-Nov-16 15:36:46 prodeo.local INFO [thi.ng.fabric.ld.core] - adding 10000 facts from [..]sales-2013-xl.edn
```

I then launched figwheel using another terminal with `lein do clean, figwheel`.

I then navigated to http://localhost:8000/index.html#query 

Here's the error I got when I pressed "submit":

```
Uncaught Error: No protocol method WritePort.put! defined for type null: 
    cljs$core$missing_protocol @ core.cljs:261
    cljs$core$async$impl$protocols$put_BANG_ @ protocols.cljs?rel=1447684436147:16
    cljs.core.async.put_BANG_.cljs$core$IFn$_invoke$arity$2 @ async.cljs?rel=1447684437523:121
    cljs$core$async$put_BANG_ @ async.cljs?rel=1447684437523:115
    (anonymous function) @ state.cljs?rel=1447684438605:98
    thi.ng.domus.io.__GT_callback @ io.cljs?rel=1447684437853:33
    (anonymous function) @ io.cljs?rel=1447684437853:63
    goog.events.EventTarget.fireListeners @ eventtarget.js:284
    goog.events.EventTarget.dispatchEventInternal_ @ eventtarget.js:381
    goog.events.EventTarget.dispatchEvent @ eventtarget.js:196
    goog.net.XhrIo.onReadyStateChangeHelper_ @ xhrio.js:864
    goog.net.XhrIo.onReadyStateChangeEntryPoint_ @ xhrio.js:809
    goog.net.XhrIo.onReadyStateChange_ @ xhrio.js:793
```

![screen shot 2015-11-16 at 15 41 35](https://cloud.githubusercontent.com/assets/8477/11184562/b2bfa4ca-8c78-11e5-935b-9728d73774c7.png)

![screen shot 2015-11-16 at 15 39 48](https://cloud.githubusercontent.com/assets/8477/11184561/b1a7bb86-8c78-11e5-8876-6a89e86fcf42.png)

**Comment by postspectacular** [comment]
Yes, thanks for effort - the query editor is the last missing piece which still needs updating. Will also check in new data files to repo, since I slightly changed the format and store gzipped (not yet committed).  think it's best to wait until I'm done with the changes...

**Comment by postspectacular** [comment]
Hi @fdb - okay, I've just checked in the "final" update, incl. result table for user queries, gzipped data, updated async init process and comments for everything. Also, check out the blog post (linked from readme).

**Comment by fdb** [comment]
Cool -- query editor works now! Thanks!
